trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages: 
- stage: Build
  displayName: Build image
  jobs:
  - job: Build    
    displayName: Build  
    pool:
      name: my-personal-computer # Replace with your self-hosted agent pool name
    steps:             
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Registry Service'
        repository: 'nourbenyahia36'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
